### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by Antonstr** [bessman/navbot#1]
Hi Alexander

The weather gave me an opportunity to have the vehicle drive itself.

The vehicle turns towards the target, breaks out of the alignment phase and starts driving towards the target. It drove over the target and when it recalculated the bearing and distance values after 10 seconds turned around to almost the initial start position and again drove to the target again driving over it.

It looks like the coordinate value for the present position is the same as the one initially used to perform the calculation as the distance to the target appears not to be updated as the vehicle drives towards the target. The distance remaining remains the same does not matter where the vehicle is in relation to the target. 

It looks like the original start coordinates are retained and not being updated as the vehicle drives towards the target

Turning from 248.3278 toward 324.05287014501914
Acquiring GPS fix...
Acquiring GPS fix...
Turning from 81.9286 toward 332.6783297762552
Driving toward target, 8.034198873005396 remaining
Driving toward target, 8.034198873005396 remaining
Turning from 340.1339 toward 327.324162224533
Turning from 338.9754 toward 326.69206471265255
Turning from 344.4165 toward 326.3117980907884
Turning from 334.8018 toward 326.24354109949616
Driving toward target, 8.034198873005396 remaining
Turning from 336.12 toward 326.7125107258457
Driving toward target, 8.034198873005396 remaining
Driving toward target, 8.034198873005396 remaining
Turning from 348.3448 toward 327.1309250286394
Turning from 343.7403 toward 325.779370984538
Turning from 341.958 toward 325.619356510693
Turning from 342.4235 toward 325.3585423334086
Turning from 345.6522 toward 324.7586501937085
Turning from 18.5438 toward 323.84504533417555
Turning from 51.459 toward 319.30353469821455
Turning from 59.7068 toward 317.6490116974371

Thank you

Sincerely

Anton

**Comment by bessman** [comment]
Yep, I forgot to update the distance calculation after entering the driving loop. Woops.

Commit b4421bdf should fix it.

**Comment by Antonstr** [comment]
Thank you

Will test as soon as the weather gives me an opportunity

Sincerely

**Comment by Antonstr** [comment]
Thank you

Tested the new code.

The vehicle performed almost as expected.

It aligned itself fairly quickly and started driving towards the target and
corrected itself every 10 seconds. The weather unfortunately cut the test
short.
It drove a little left to right to left instead of a straight line.

The vehicle is also to slow for the gps data to be "stable" and does not
achieve RTK Fixed status

The minimum speed for the vehicle to start receiving the "track" value is
around 0.15 m/s which is not that fast.

Presently the vehicle is too underpowered to maintain such speeds over
uneven terrain.

New motors are at the order of the day and I will know on either Thursday
or Friday when I will have my more powerful motors that will be able to
maintain 300 mm per second, double the speed required.

The results should be a lot better

Below is a screen grab of part of the vehicles navigation effort


4.149076809667727 to target

Turning left from 242.2037 toward 215.62801810971683

4.202427113165675 to target

Turning right from 0.0 toward 215.45482095365267

4.220247065246678 to target

Heading straight (track {track} vs. bearing {bearing})

4.236864629783365 to target

Turning left from 235.5696 toward 215.20675514808366

4.2428073371719925 to target

Turning left from 243.8584 toward 214.4132048822402

4.1731755405731965 to target

Heading straight (track {track} vs. bearing {bearing})

4.08866626921753 to target

Heading straight (track {track} vs. bearing {bearing})

4.055610189671277 to target

Turning right from 0.0 toward 214.87458367944748

Sincerely

Anton
